language: java
install: true
jdk:
 - oraclejdk8
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
app: game-of-three-hisham

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
